services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    env_file:
      - .env
    command: yarn start:prod
    ports:
      - 3001:3001
